<?php

namespace DoctrineProxies\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produto extends \Application\Entity\Produto implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ativo' => [parent::class, 'ativo', null, 16],
        "\0".parent::class."\0".'descricao' => [parent::class, 'descricao', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'marca' => [parent::class, 'marca', null, 16],
        "\0".parent::class."\0".'nome' => [parent::class, 'nome', null, 16],
        "\0".parent::class."\0".'preco' => [parent::class, 'preco', null, 16],
        "\0".parent::class."\0".'quantidade' => [parent::class, 'quantidade', null, 16],
        "\0".parent::class."\0".'setor' => [parent::class, 'setor', null, 16],
        'ativo' => [parent::class, 'ativo', null, 16],
        'descricao' => [parent::class, 'descricao', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'marca' => [parent::class, 'marca', null, 16],
        'nome' => [parent::class, 'nome', null, 16],
        'preco' => [parent::class, 'preco', null, 16],
        'quantidade' => [parent::class, 'quantidade', null, 16],
        'setor' => [parent::class, 'setor', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
