<?php

namespace DoctrineProxies\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Application\Entity\Usuario implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nome' => [parent::class, 'nome', null, 16],
        "\0".parent::class."\0".'senha' => [parent::class, 'senha', null, 16],
        "\0".parent::class."\0".'setor' => [parent::class, 'setor', null, 16],
        "\0".parent::class."\0".'setorResponsavel' => [parent::class, 'setorResponsavel', null, 16],
        "\0".parent::class."\0".'tipo' => [parent::class, 'tipo', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nome' => [parent::class, 'nome', null, 16],
        'senha' => [parent::class, 'senha', null, 16],
        'setor' => [parent::class, 'setor', null, 16],
        'setorResponsavel' => [parent::class, 'setorResponsavel', null, 16],
        'tipo' => [parent::class, 'tipo', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
