<div class="p-5 mb-4 bg-light rounded-3">
    
    <?php if ($this->nomeUsuario): ?>
        <h1 class="display-4">Bem-vindo, <?= $this->escapeHtml($this->nomeUsuario) ?>!</h1>
        <p>Você está logado no Sistema de Estoque Três Glórias.</p>
        <p>
            </p>

    <?php else: ?>
        <h1 class="display-4">Bem-vindo ao Sistema de Estoque</h1>
        <p>Por favor, faça o login para continuar.</p>
        <p>
            <a class="btn btn-primary btn-lg" href="<?= $this->url('login') ?>">Fazer Login</a>
        </p>
    <?php endif; ?>

</div>